[package]
name = "wmanager"
version = "0.1.0"
edition = "2021"

[lib]
name = "libwm"
path = "src/libwm/lib.rs"

[[bin]]
name = "wmanager"
path = "src/bin.rs"

[dependencies]
xcb = "1.4.0"
anyhow = "1.0"