version: '3.4'


services:

  xserver:
    image: suchja/x11server
    container_name: xserver
    user: root
    environment:
      - VNC_PASSWORD=tester
      - XFB_SCREEN=1280x800x24
      - XFB_SCREEN_DPI=150
    command: 
      - "-create"
    ports:
      - "5900:5900"
      - "6000:6000"
    networks:
      lan:
        aliases:
          - xserver.lan.com 
  xclient:
    build: ./docker/xclient
    container_name: xclient
    networks:
      lan:
        aliases:
          - xclient.lan.com
networks:
  lan:
    driver: bridge
    
